### ISSUE TITLE
Any chance of LGPL license?

### ISSUE THREAD

**Issue by ipsod** [MrYsLab/python_banyan#34]
Hi Mr. Y.

I'm an independent developer evaluating Banyan as a lightweight alternative to ROS, but I'm not sure if I can work with the GPL license.

Might the LGPL accomplish your intended goal?

**Comment by MrYsLab** [comment]
Hi @ipsod,
   Thank you for asking. The reason for using AGPL is that it closes the so-called _Web Loophole_ contained in LGPL. Since Banyan uses a network as part of its design, I feel that AGPL is the proper license for me to use.
Looking at this [FOSSA article](https://fossa.com/blog/open-source-software-licenses-101-agpl-license/),  the only significant restriction is that your code would need to adopt AGPL as well.

**Comment by ipsod** [comment]
Thank you for the resposne.

I believe that LGPL3.0 still closes the web loophole - it's just that it only requires I share modifications to your library, and not my entire codebase.

I have thousands of hours of work into my project, and I think that Banyan would save me perhaps 2 days of work over just using ZMQ.  I'm not planning to change my business model and life plan over that, and hoped that you might reconsider your licensing.

**Comment by MrYsLab** [comment]
It would take me more than two days to change license types, and in my opinion, with no advantage to me.
Therefore, the license will remain AGPL.
Thanks for asking, though.

**Comment by ipsod** [comment]
Ok, thanks anyway.

**Comment by ipsod** [comment]
I hope I didn't come across as rude.  I didn't mean to imply it was worth changing your license for my use alone, but to provide my own case as an example.
